name: Deploy site

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 5 * * 2-6"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
            cache: true

      - name: Install dependencies
        run: pdm install

      - name: Cache flatfiles
        id: cache-flatfiles
        uses: actions/cache@v4
        with:
            path: flatfiles/
            key: ${{ runner.os }}-flatfiles

      - name: Download flatfiles
        run: pdm run python src/hvc_finder/download.py
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Generate HTML
        run: pdm run python src/hvc_finder/build_page.py

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
